### PR TITLE
Update ember-test-helpers to 0.5.0.

### PR DESCRIPTION
**Pull request by trombom**
- Stay in sync with ember-qunit

See https://github.com/rwjblue/ember-qunit/commit/38122a72b630a61057d68e5f877ffa82caea3999
for more information

### CODE REVIEW

**Comment by trombom** [comment]
Note they made a minor version bump to ember-qunit when doing this, thus we'll need to update ember-cli-mocha if we do the same.

I can make that change too, let me know

**Comment by kiwiupover** [comment]
:100:

**Comment by dgeb** [comment]
Released in ember-mocha v0.8.0 :shipit: 

Still waiting to clarify an issue in ember-cli-mocha before cutting a new release.

**Comment by kiwiupover** [comment]
Thanks @dgeb We are using ember mocha at godaddy.com and it's been great for us. 

What is the best way for us to help you with the project?

**Comment by dgeb** [comment]
@kiwiupover that's great to hear :)

> What is the best way for us to help you with the project?

I'm not always working with ember-mocha in my day-to-day development, so your input on issues would be much appreciated. And of course, we're trying to keep feature parity with ember-qunit. Contributions are always welcome - thanks!

**Pull request merged**
