### PR TITLE
Expose chai configuration object

### PR DESCRIPTION
**Pull request by mupkoo**
Expose chai's configuration options to allow fine tune it - http://chaijs.com/guide/styles/#configure-section

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks good. Can you squash commits?

**Comment by mupkoo** [comment]
It's the first time I am squashing commits :)

**Comment by rwjblue** [comment]
Looks great! Thank you!

**Comment by rwjblue** [comment]
Published as v0.8.6.

**Pull request merged**
