### PR TITLE
New testing API

### PR DESCRIPTION
**Pull request by Turbo87**
The old testing API is sort-of using inheritance on the `describe()` function to setup and teardown all the necessary pieces. The proposed new testing API is using composition instead via the new `setupModuleTest()` functions.

- [x] Replace custom `it()` with original from Mocha
- [x] Extract new `setupModuleTest()` and related functions
- [x] Add tests for the new functions
- [x] Update README to the new API
- [x] Add deprecation messages to the old API

Before:

```js
import { expect } from 'chai';
import { describeModule, it } from 'ember-mocha';

describeModule(
  'controller:users',
  'Unit | Controller | users',
  {
    // Specify the other units that are required for this test.
    // needs: ['controller:foo']
  },
  function() {
    // Replace this with your real tests.
    it('exists', function() {
      let controller = this.subject();
      expect(controller).to.be.ok;
    });
  }
);
```

After: 

```js
import { expect } from 'chai';
import { it, describe } from 'mocha';
import { setupModuleTest } from 'ember-mocha';

describe('Unit | Controller | users', function() {
  setupTest('controller:users', {
    // Specify the other units that are required for this test.
    // needs: ['controller:foo']
  });

  // Replace this with your real tests.
  it('exists', function() {
    let controller = this.subject();
    expect(controller).to.be.ok;
  });
});

```

/cc @rwjblue @stefanpenner

### CODE REVIEW

**Comment by rwjblue** [comment]
I like it!  Would like @dgeb and/or @stefanpenner to review also.

Definitely need deprecations on the existing things I think...

**Comment by dgeb** [comment]
I like this approach too. I'm in favor of using mocha's `describe` and `it` instead of overriding.

My only real issue is with the method name `setupModuleTest`. Can we drop `Module` and just go with `setupTest`? Then there would be `setupTest`, `setupModelTest`, `setupComponentTest`, and `setupAcceptanceTest`.

I regret cargo-culting the term `Module` over from QUnit (and ember-qunit) and this seems a good chance to drop it.

Open to suggestions here.

**Comment by Turbo87** [comment]
@dgeb I'd be fine with `setupTest()`, although in the future we might switch to `setupUnit/Integration/AcceptanceTest()` anyway once the RFC of @rwjblue gets implemented.

**Comment by dgeb** [comment]
Yes, good to consider the implications of the testing RFC and aim for consistency with ember-qunit.

**Comment by Turbo87** [comment]
pinging mr. @cowboyd! @rwjblue said you might have an opinion on this too and he would like to hear it... 😉

**Comment by Turbo87** [comment]
@dgeb renamed it to `setupTest()`

@rwjblue added the deprecation message

should be good to go now unless you have any more suggestions

**Comment by cowboyd** [comment]
@Turbo87 This looks like a much welcome improvement!

**Comment by Turbo87** [comment]
@rwjblue can we merge this? any more comments?

**Comment by Turbo87** [comment]
1️⃣ 2️⃣ 3️⃣ :shipit:

**Comment by rwjblue** [comment]
I'm 👍 .  I'd like a 👍 /:-1: from @dgeb and/or @trentmwillis before landing...

**Comment by Turbo87** [comment]
Given that I addressed everything in https://github.com/switchfly/ember-mocha/pull/84#issuecomment-239462513 I assumed that he was 👍  too

**Comment by Turbo87** [comment]
@dgeb @trentmwillis ping 😉

**Comment by trentmwillis** [comment]
:+1: didn't review the code, but I agree with this approach. Primarily, I like that it provides better separation between the default test framework and the Ember-specific test helpers. I also believe this will make it easier to retain all the default behaviors of the underlying framework (something we've had issues with in ember-qunit).

**Comment by dgeb** [comment]
> Given that I addressed everything in #84 (comment) I assumed that he was 👍 too

Yep, thanks for addressing my concerns @Turbo87. Let's ship this! :shipit:

**Comment by Turbo87** [comment]
🎉

**Comment by Turbo87** [comment]
@dgeb @rwjblue any plans for a 0.9 release?

**Pull request merged**
